### ISSUE TITLE
Planteamiento y estructuración de la arquitectura

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#1]
Se hizo el planteamiento de usar la arquitectura por microservicios para el presente proyecto.

**Comment by Mik43la** [comment]
Plantear la arquitectura fue un poco complicado pero se llegó a un acuerdo entre los integrantes del grupo.

**Comment by AleS900** [comment]
Pese a las dificultades se logró llegar a una decisión con la que todos los integrantes estaban de acuerdo.
