### ISSUE TITLE
Caso de uso: Venta de plantas

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#10]
El sistema deberá verificar que el usuario tenga una cuenta registrada en el sistema.
El sistema debe permitir al usuario consultar información, actualizar y verificar el stock, registrar ventas y eliminar el registro de ventas previas.
El sistema debe permitir al administrador asignar bonos de pago a los empleados.

**Comment by AleS900** [comment]
Se logró de manera satisfactoria, reflejar el "Módulo Venta de Plantas", a través de los casos de uso, de la siguiente manera:

![image](https://user-images.githubusercontent.com/60782047/142858255-63192753-7125-42f1-bf88-6002878d8783.png)
