### ISSUE TITLE
Casos De Uso Completados - Módulo: Venta De Plantas

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#100]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso  - Módulo: Venta De Plantas, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de ralizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Nachin7u7** [comment]
El numero de ventas de las plantas se denota en el dashboard donde se percata que el back-end de dicha penstaña ha de funcionar de acuerdo al plan
