### ISSUE TITLE
Casos De Uso Completados - Módulo: Proveedores de Insumo

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#101]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso - Módulo: Proveedores de Insumos, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Mik43la** [comment]
Revisión importante para el funcionamiento sin error alguno del módulo de proveedores de insumos. Esta tarea debe ser realizada con cuidado y atención.
