### ISSUE TITLE
Casos De Uso Completados - Módulo: Reportes

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#102]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso - Módulo: Reportes, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Mik43la** [comment]
Revisión importante para el funcionamiento fluido y correcto del módulo de reportes. Esta tarea debe ser realizada con cuidado y atención.
