### ISSUE TITLE
Casos De Uso Completados - Módulo: Mantención de Empleados

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#103]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso - Módulo: Mantención de Empleados, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Nachin7u7** [comment]
La actualización de base de datos de los empleados con respecto a los usuarios con rol de empleados tiene un buen punto de donde partir en su use-case, a lo cual se vio que esta teniendo la forma tal cual se plantea en el diagrama
