### ISSUE TITLE
Casos De Uso Completados - Módulo: Reserva de Plantas

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#104]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso - Reserva de plantas: se revisará el correcto funcionamiento de la pestaña y se verá el request de las tablas para ver en la pagina la cantidad, precio, en general que hay en reserva. También se ingresará datos erróneos y raros para encontrar bugs en la pagina.

**Comment by Nachin7u7** [comment]
La reserva de plantas esta teniendo forma en back-end con buena UX donde se plantea un uso bueno para cualquier individuo
