### ISSUE TITLE
Casos De Uso Completados - Módulo: Gestión de Depósito

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#105]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso - Módulo: Gestión de Depósitos, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Nachin7u7** [comment]
La gestión de depósito nos muestra una excelente implementación de uso donde se ve la cantidad de productos en stock, precios y otras variantes de los atributos que se usarán en otras pestañas
