### ISSUE TITLE
Casos De Uso Completados - Módulo: Mantención de Usuarios

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#106]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso - Módulo: Mantención de Usuarios, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Mik43la** [comment]
Esta tarea es muy importante para el funcionamiento correcto del módulo de mantención de usuarios. Esta tarea debe ser realizada con cuidado y atención.
