### ISSUE TITLE
Casos De Uso Completados - Módulo: Mantención de Clientes

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#107]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso - Módulo: Mantención de Clientes, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Nachin7u7** [comment]
Ciertos bugs se encontraron y tratamos los mismos testeando codigo diferente
