### ISSUE TITLE
Caso de uso: Proveedores de insumo

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#11]
El sistema deberá verificar que el usuario tenga una cuenta registrada en el sistema.
El sistema debe permitir al usuario consultar información, verificar el stock, registrar proveedores, modificar y eliminar proveedor.

**Comment by AleS900** [comment]
Se logró de manera satisfactoria el reflejar el "Módulo de Proveedores de Insumo", con todas los requisitos subsecuentes al mismo, como se puede ver a continuación:

![image](https://user-images.githubusercontent.com/60782047/142857885-69f1b116-fed6-4b4e-9e5d-32646e17b87e.png)
