### ISSUE TITLE
Corrección de Errores

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#114]
Se procederá  a hacer una revisión de todo el proyecto para encontrar cualquier tipo de error o problema que haya podido existir, de esta manera cumplir con los requisitos propuestos para la entrega del trabajo.

**Comment by Mik43la** [comment]
Esta revisión es de suma importancia para comprobar que no haya ningún error o falla en el proyecto, si se llega a encontrar uno se debe trabajar en solucionarlo de manera inmediata.
