### ISSUE TITLE
Caso de uso: Reportes

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#12]
El sistema deberá verificar que el usuario tenga una cuenta registrada en el sistema.
El sistema debe permitir al administrador generar informes, realizar reportes de producción, reportes de ventas, reportes de inventarios y reportes de kardex.

**Comment by AleS900** [comment]
Se realizó un caso de uso que refleja de manera satisfactoria el "Módulo De Reportes",  como se puede ver a continuación:

![image](https://user-images.githubusercontent.com/60782047/142857670-7c637ecd-98db-423a-ba39-003c42890405.png)
