### ISSUE TITLE
Caso de uso: Mantención de empleado

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#13]
El sistema deberá verificar que el usuario tenga una cuenta registrada en el sistema.
El sistema debe permitir al administrador registrar nuevos empleados, consultar información, eliminar empleados y registrar modificaciones sobre la información de empleados.

**Comment by AleS900** [comment]
Se realizó un caso de uso que refleja de manera satisfactoria el Módulo Gestión de empleados como se puede ver a continuación:

![image](https://user-images.githubusercontent.com/60782047/142857538-dcbf67b6-01fc-4b26-a866-fef3ce7237a0.png)
