### ISSUE TITLE
Mockup inicio de sesión.

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#14]
Se elaboró un Mockup Correspondiente a la pantalla de "Incio de Sesión".

**Comment by AleS900** [comment]
La tarea se elaboró utilizando la plataforma Uizard, con un resultado satisfactorio.

![image](https://user-images.githubusercontent.com/60782047/142624356-fc0bf2f4-4d65-4028-86c0-59d444b86a87.png)

**Comment by Nachin7u7** [comment]
el log in se ve profesional y como una pagina web genérica
