### ISSUE TITLE
Mockup pantalla home, pestaña de reservas desplegada.

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#17]
Se elaboró un Mockup Correspondiente a la pantalla Inicio / Reservas.
Que correponde a la pantalla de Inicio con la pestaña de Reservas desplagada.

**Comment by Nachin7u7** [comment]
bastante llamativo, a demás de util

**Comment by AleS900** [comment]
La tarea se elaboró utilizando la plataforma Uizard, con un resultado satisfactorio.

![image](https://user-images.githubusercontent.com/60782047/142824528-25a1f12d-9019-4d02-9a2e-ba5b13713bc9.png)
