### ISSUE TITLE
Mockup pantalla home, pestaña de inventario desplegada.

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#18]
Se elaboró un Mockup Correspondiente a la pantalla Inicio / Inventario.
Que correponde a la pantalla de Inicio con la pestaña de Inventario desplagada.

**Comment by Nachin7u7** [comment]
Muy intuitivo para cualquier usuario

**Comment by AleS900** [comment]
La tarea se elaboró utilizando la plataforma Uizard, con un resultado satisfactorio.

![image](https://user-images.githubusercontent.com/60782047/142825044-9ff59625-4991-4d90-861f-db5b4577882e.png)
