### ISSUE TITLE
Mockup pantalla home, pestaña de procesos desplegada.

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#19]
Se elaboró un Mockup Correspondiente a la pantalla Inicio / Procesos.
Que correponde a la pantalla de Inicio con la pestaña de Procesos desplagada.

**Comment by Nachin7u7** [comment]
Muy grafico lo que da mucha información al respecto

**Comment by AleS900** [comment]
La tarea se elaboró utilizando la plataforma Uizard, con un resultado satisfactorio.

![image](https://user-images.githubusercontent.com/60782047/142825545-50c4edaf-2035-4cdc-aa87-8386bb66ffbe.png)
