### ISSUE TITLE
Elección del software y aplicaciones a utilizar

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#2]
Escoger el software y aplicaciones que se van a utilizar para la elaboración del proyecto.

**Comment by Mik43la** [comment]
Esta tarea fue sencilla y rápida.
Entre los integrantes del grupo se propuso diversas herramientas y se hizo la elección de aplicaciones con eficacia.

**Comment by AleS900** [comment]
Se propuesieron distintas alternativas, llegando a un acuerdo de manera rápida.
