### ISSUE TITLE
Mockup pantalla home, pestaña de clientes desplegada.

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#23]
Se elaboró un Mockup Correspondiente a la pantalla Inicio / Clientes .
Que correponde a la pantalla de Inicio con la pestaña de Clientes desplagada.

**Comment by Nachin7u7** [comment]
Buena iteración con los clientes en front-end

**Comment by AleS900** [comment]
La tarea se elaboró utilizando la plataforma Uizard, con un resultado satisfactorio.

![image](https://user-images.githubusercontent.com/60782047/142826924-4aec90a3-b952-434b-a155-25d7a9b4ebf2.png)
