### ISSUE TITLE
Mockup pantalla home, pestaña de registros desplegada.

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#24]
Se elaboró un Mockup Correspondiente a la pantalla Inicio / Registros.
Que correponde a la pantalla de Inicio con la pestaña de Registros desplagada.

**Comment by Nachin7u7** [comment]
Vista amigable para todo tipo de registros

**Comment by AleS900** [comment]
La tarea se elaboró utilizando la plataforma Uizard, con un resultado satisfactorio.

![image](https://user-images.githubusercontent.com/60782047/142827170-b6350a24-f6c6-4d21-8777-d71214574199.png)
