### ISSUE TITLE
caso de uso: módulo reserva de plantas

### ISSUE THREAD

**Issue by Nachin7u7** [Daily-Crisis/Daily-Crisis#26]
El sistema tiene que permitir al administrador revisar peticiones del cliente, ingresar reservas al sistema, validarlas y/o anularlas. 
El administrador debe poder actualizar el stock, consultar reservas de clientes y reservas de productos existentes en el sistema.

**Comment by Mik43la** [comment]
Se pensó en las diversas tareas que un administrador debería poder realizar para el manejo de reservas. Se terminó con este diagrama.
