### ISSUE TITLE
caso de uso: mantención de Usuarios

### ISSUE THREAD

**Issue by Nachin7u7** [Daily-Crisis/Daily-Crisis#27]
El sistema deberá permitir a un usuario ingresar a su perfil introduciendo sus datos.
El usuario deberá poder añadir su información al sistema, editarla, eliminarla y poder mostrar la información de su perfil.

**Comment by Mik43la** [comment]
Se pensó en acciones básicas para los usuarios. Los usuarios tienen que iniciar sesión antes de realizar cualquier cambio a su perfil.
