### ISSUE TITLE
caso de uso: módulo gestión de depósito

### ISSUE THREAD

**Issue by Nachin7u7** [Daily-Crisis/Daily-Crisis#28]
El administrador debe poder ingresar los datos de un insumo, su proveedor y modificar los datos de ambos.
El administrador debe ser capaz de verificar el stock, mostrar la información de insumos y poder eliminarlos.

**Comment by Mik43la** [comment]
Se pensó en las acciones que un administrador debería poder realizar para gestionar el manejo de un deposito. Se terminó con este diagrama de caso de uso.
