### ISSUE TITLE
Identificar las distintas tareas a realizar

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#3]
Se debe identificar las diversas tareas a realizar a lo largo de la elaboración del proyecto

**Comment by Mik43la** [comment]
Esta tarea fue un poco morosa debido al tamaño del proyecto

**Comment by AleS900** [comment]
La tarea fue un poco difícil debido a la extensión del proyecto, sin embargo, pese a eso se logó elaborar dicha tarea de manera satisfactoria.
