### ISSUE TITLE
Escribir sobre la arquitectura general del proyecto

### ISSUE THREAD

**Issue by Nachin7u7** [Daily-Crisis/Daily-Crisis#46]
Se realizó la investigación y la descripción de que tipo de arquitectura usaremos.

**Comment by AleS900** [comment]
Se elaboraron esquemas en función de las decisiones tomadas:

Para Frontend:

![WhatsApp Image 2021-11-21 at 20 11 17](https://user-images.githubusercontent.com/60782047/142828049-ea439244-8f18-4856-b853-60efaeb77f93.jpeg)

Para Backend:

![WhatsApp Image 2021-11-21 at 20 13 31](https://user-images.githubusercontent.com/60782047/142828078-b74fab55-1bcf-476d-bb88-38b63d95661f.jpeg)
