### ISSUE TITLE
Cargar esquemas en el sistema

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#58]
Se deberá cargar los esquemas realizados a la Wiki

**Comment by Mik43la** [comment]
Fue una tarea rápida de realizar.

**Comment by AleS900** [comment]
Los esquemas resultaron en:

![emavra db diagram](https://user-images.githubusercontent.com/60782047/145024683-1071657a-dbfa-4202-a0a7-c7637e73b40f.png)

![IMG-20211125-WA0001](https://user-images.githubusercontent.com/60782047/145024707-a6e7dccd-52e7-4667-b6d9-e889f71ac590.jpg)

![143576208-1f93d8b8-82cb-4b8e-8037-264e9eb90391](https://user-images.githubusercontent.com/60782047/145024737-d496c15d-27d1-4595-807d-04a74c8cfab3.png)

![iniciar_sesion-copy](https://user-images.githubusercontent.com/60782047/145024759-9c345fa0-93d7-4b98-90d5-cb05b073647a.jpg)
