### ISSUE TITLE
Escribir los requerimientos generales en la wiki 

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#6]
Documentar la información de los requerimientos generales del proyecto en la wiki.

**Comment by AleS900** [comment]
Se logró identificar los requerimientos generales del proyecto, reflejando dicho trabajo plasmándolo en la Wiki. Así  como se puede ver en los siguientes extractos:
- Requerimientos Funcionales:

![image](https://user-images.githubusercontent.com/60782047/142859182-1cc93c43-b418-4b39-bb17-03f9df6c49c7.png)

- Requerimientos No Funcionales:
![image](https://user-images.githubusercontent.com/60782047/142859132-0ca5a15f-add3-4238-ab28-b941bbde03f3.png)
