### ISSUE TITLE
Escribir la introducción de los casos de uso en la wiki

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#8]
Documentar información de los casos de uso en la wiki del projecto.

**Comment by AleS900** [comment]
Se logró previo a una reunión del grupo elaborar una introducción que introduzca de manera eficiente el tema de los casos de uso de la presente wiki, como se puede apreciar a continuación:

![image](https://user-images.githubusercontent.com/60782047/142858695-498f9c4e-6598-46b9-8a44-e8b6615b4e29.png)
