### ISSUE TITLE
Caso de uso: Gestión de procesos

### ISSUE THREAD

**Issue by Mik43la** [Daily-Crisis/Daily-Crisis#9]
El sistema deberá verificar que el usuario tenga una cuenta registrada en el sistema.
El sistema debe permitir al usuario registrar eventos, sembrados y abonos.
El sistema deberá mandar notificaciones de los eventos pendientes.

**Comment by AleS900** [comment]
Se logró a través de la utilziación de esta herramienta el reflejar el "Módulo de Gestión de Procesos", como se puede apreciar a continuación:

![image](https://user-images.githubusercontent.com/60782047/142858445-08d39b03-acb1-4240-9198-cc7b579b2ee6.png)
