### ISSUE TITLE
CRUD de Usuarios con Diferentes Roles - CREATE

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#94]
Se revisará si el proyecto cumple con todos los requerimientos que conlleva el CREATEde un CRUD de una Base de Datos, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Nachin7u7** [comment]
Agregar usuarios de manera intuitiva para una interfaz útil para que los usuarios de la aplicacion no tengan problemas al crear un usuario con un rol
