### ISSUE TITLE
CRUD de Usuarios con Diferentes Roles - READ

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#95]
Se revisará si el proyecto cumple con todos los requerimientos que conlleva el READ de un CRUD de una Base de Datos, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Nachin7u7** [comment]
La lectura de usuarios desde la base de datos dando a conocer que tipo de usuario es denota un buen UI para el usuario que usa la pagina
