### ISSUE TITLE
CRUD de Usuarios con Diferentes Roles - UPDATE

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#96]
Se revisará si el proyecto cumple con todos los requerimientos que conlleva el UPDATE de un CRUD de una Base de Datos, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Nachin7u7** [comment]
Actualizar la información es parecida a la creación de usuarios con el detalle que es en una pagina diferente donde te pide hacer un override en de ciertos atributos del usuario
