### ISSUE TITLE
CRUD de Usuarios con Diferentes Roles - DELETE

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#97]
Se revisará si el proyecto cumple con todos los requerimientos que conlleva el DELETE de un CRUD de una Base de Datos, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisón de aquellos puntos que no estan correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Nachin7u7** [comment]
Se está dando un diferente enfoque a cada usuario para cada uso distinto
