### ISSUE TITLE
Login Usuarios Recientemente Creados

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#98]
La página debe ser apta para lograr ingresar con cualquier cuenta que se encuentre en la base de datos, donde el login hace su búsqueda  para dar un rol y ver que dashboard se cargará al dicho usuario.

**Comment by Nachin7u7** [comment]
Añadir en la base de datos el usuario y la contraseña de tal forma que el request que se hace en el login busque entre la tabla el usuario y contraseña
