### ISSUE TITLE
Casos De Uso Completados - Módulo: Gestión de Procesos

### ISSUE THREAD

**Issue by AleS900** [Daily-Crisis/Daily-Crisis#99]
Se revisará si el proyecto cumple con todos los requerimientos del Caso De Uso - Módulo: Gestión de Procesos, si esto es correcto se procederá a determinar la tarea como completada, caso contrario se debe de realizar una revisión de aquellos puntos que no están correctamente implementados y se procederá a tratar de integrarlos.

**Comment by Mik43la** [comment]
Revisión importante para el funcionamiento sin errores del módulo de gestión de procesos. Esta tarea debe ser realizada con cuidado y atención.
